### ISSUE TITLE
Dependency missing in `library.properties` file

### ISSUE THREAD

**Issue by lboue** [esp-arduino-libs/ESP32_Display_Panel#90]
Hello,

Would it be possible to add the libraries used in the examples as a dependency of this library?
For exemple:
- ArduinoJson
- NTPClient
- LVGL 8.3.x

This would avoid having to manually install the libraries to test the examples.

https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/289d3575fee397d5ef80e10576b92497299db4a2/library.properties#L11

Regards

**Comment by Lzw655** [comment]
Hi @lboue,

The example documentation and .ino file specify the dependent libraries and their versions. And I believe that only the components that the source code under src depends on should be considered fixed dependencies. This follows the principle of minimal dependencies. Otherwise, if future examples rely on more components, adding all of them as fixed dependencies wouldn't be elegant.

**Comment by lboue** [comment]
OK I understand the reasoning even if I don't find it practical.

**Comment by Lzw655** [comment]
Thanks for your understanding! And please feel free to provide your suggestions.
